-- Phase 3B protocol v2 immutable payload. Phase 3A sliders are deliberately
-- not used here: Lua writes a complete gmem page, then publishes its commit.
local M={MAGIC=52444,VERSION=2,SCHEMA=1,MAX_WORDS=262144,MAX_PATTERNS=8,MAX_VARIATIONS=64,MAX_LANES=128,MAX_STEPS=14000,MAX_GROOVE_STEPS=256,MAX_PADS=128,MAX_LINKS=4,MAX_GROUPS=32,MAX_GROUP_MEMBERS=16,MAX_LOCKS=4096}
M.TAG={PATTERN=1,VARIATION=2,LANE=3,STEP=4,PAD=5,LOCK=6,GROUP=7,GROOVE=8,END_=255}
M.CONDITION={always=0,first=1,not_first=2,every_n=3,fill=4,not_fill=5,previous=6}
M.QUANT={immediate=0,step=1,beat=2,bar=3,pattern=4}
M.RR_MODE={sequential=0,ping_pong=1,random=2,random_no_repeat=3}
M.RR_RESET={never=0,pattern=1,transport=2,trigger=3}
local function die(path,msg) error(path..": "..msg,3) end
local function integer(v,path,lo,hi) if type(v)~="number"or v~=math.floor(v)or v<lo or v>hi then die(path,"integer out of range ["..lo..","..hi.."]")end return v end
local function hash(s,path)local h=2166136261;if type(s)~="string"or s==""then die(path,"non-empty ID required")end;for i=1,#s do h=(h~s:byte(i))*16777619%2147483647 end;return h end
local function ppm(v,path)local hi=path=="Step.gate"and 1600 or 100;if type(v)~="number"or v<0 or v>hi then die(path,"number out of range [0,"..hi.."]")end;return math.floor(v*10000+0.5)end
local function rat(v,path)if type(v)=="number"then if v<=0 then die(path,"positive rational required")end;return math.floor(v*1000000+0.5),1000000 end;if type(v)~="table"then die(path,"rational required")end;return integer(v.numerator,path..".numerator",1,2147483647),integer(v.denominator,path..".denominator",1,2147483647)end
local function add(w,tag,fields)local start=#w+1;w[start]=tag;w[start+1]=#fields;for i,v in ipairs(fields)do w[start+1+i]=v end end
local function checksum(w,first)local c=1;for i=first or 1,#w do c=(c*48271+(w[i]%2147483647))%2147483647 end;return c end
local function quant(q,path)if type(q)=="string"then local x=M.QUANT[q];if x==nil then die(path,"unsupported named quantization")end;return x,0,1 end;local n,d=rat(q,path);return 5,n,d end
local function condition(c,path,lane_refs)local k=M.CONDITION[c.type];if k==nil then die(path,"unsupported condition '"..tostring(c.type).."'")end;if k==3 then return k,integer(c.n,path..".n",1,2147483647),integer(c.offset or 0,path..".offset",0,c.n-1)elseif k==6 then local target=0;if c.lane_id then target=lane_refs[c.lane_id]or die(path..".lane_id","must name a lane in the same variation")end;return k,c.state=="hit"and 1 or c.state=="miss"and 0 or die(path..".state","expected hit or miss"),target end;return k,0,0 end
function M.encode(rack,opt)
 opt=opt or{};local tick=opt.yield_hook or function()end;if type(rack)~="table"or rack.type~="Rack"then die("Rack","Rack is required")end
 local rev=integer(opt.revision or 1,"revision",0,16777215);local active=integer(opt.active_variation or 0,"active_variation",0,M.MAX_VARIATIONS);local pending=integer(opt.pending_variation or 0,"pending_variation",0,M.MAX_VARIATIONS)
 local w={M.MAGIC,M.VERSION,M.SCHEMA,0,0,rev,active,pending,0,0,0,0,0,0,0,0};local ids={};local function hid(id,path)local h=hash(id,path);if ids[h]and ids[h]~=id then die(path,"ID hash collision")end;ids[h]=id;return h end
 local pads={};for _,p in ipairs(rack.pads or{})do pads[p.id]=p end
 if #(rack.pads or{})>M.MAX_PADS then die("Rack.pads","capacity exceeded")end
 for pi,p in ipairs(rack.pads or{})do tick();local f={integer(p.logical_index,"Pad.logical_index",1,128),hid(p.id,"Pad.id"),p.choke_group==false and 0 or integer(p.choke_group,"Pad.choke_group",1,32),p.self_choke and 1 or 0,integer(p.polyphony,"Pad.polyphony",1,128),#p.simultaneous_play_targets}
  if #p.simultaneous_play_targets>M.MAX_LINKS or #p.mute_targets>M.MAX_LINKS then die("Pad["..pi.."]","relationship capacity exceeded")end
  for i=1,M.MAX_LINKS do local id=p.simultaneous_play_targets[i];f[#f+1]=id and integer(assert(pads[id],"unknown simultaneous target").logical_index,"target",1,128)or 0 end;f[#f+1]=#p.mute_targets;for i=1,M.MAX_LINKS do local id=p.mute_targets[i];f[#f+1]=id and integer(assert(pads[id],"unknown mute target").logical_index,"target",1,128)or 0 end;local controls=p.default_controls or{};local pan=controls.pan;if pan==nil then pan=.5 end;if type(pan)~="number"or pan<0 or pan>1 then die("Pad["..pi.."].default_controls.pan","normalized number out of range [0,1]")end;f[#f+1]=math.floor((pan*2-1)*100+(pan>=.5 and .5 or-.5));f[#f+1]=p.sample~=false and p.sample~=nil and 1 or 0;f[#f+1]=controls.legato_enabled==false and 0 or 1;add(w,M.TAG.PAD,f)end
 local groups=rack.round_robin_groups or{};if #groups>M.MAX_GROUPS then die("Rack.round_robin_groups","capacity exceeded")end
 for gi,g in ipairs(groups)do tick()
  if #g.member_pad_ids<2 or #g.member_pad_ids>M.MAX_GROUP_MEMBERS then die("RoundRobinGroup["..gi.."]","member capacity exceeded")end
  local mode=M.RR_MODE[g.mode];local reset=M.RR_RESET[g.reset_policy];if mode==nil or reset==nil then die("RoundRobinGroup["..gi.."]","unsupported mode/reset")end
  local master=assert(pads[g.master_pad_id],"unknown round robin master");local f={integer(master.logical_index,"master",1,128),mode,ppm(g.probability,"probability"),reset,integer(g.seed,"seed",0,2147483647),g.advance_on_skip and 1 or 0,g.advance_each_repeat and 1 or 0,#g.member_pad_ids}
  for i=1,M.MAX_GROUP_MEMBERS do local id=g.member_pad_ids[i];f[#f+1]=id and integer(assert(pads[id],"unknown round robin member").logical_index,"member",1,128)or 0 end;add(w,M.TAG.GROUP,f)
 end
 local vc,lc,sc,locks=0,0,0,0;if #(rack.patterns or{})>M.MAX_PATTERNS then die("Rack.patterns","capacity exceeded")end
 for pi,p in ipairs(rack.patterns or{})do tick();add(w,M.TAG.PATTERN,{hid(p.id,"Pattern.id"),integer(p.seed,"Pattern.seed",0,2147483647),#p.variations});for vi,v in ipairs(p.variations)do tick();vc=vc+1;if vc>M.MAX_VARIATIONS then die("Variation","capacity exceeded")end;local q,qn,qd=quant(v.switch_quantization,"Variation.switch_quantization");add(w,M.TAG.VARIATION,{hid(v.id,"Variation.id"),pi,q,qn,qd,#v.lanes});if v.groove then local g=v.groove;local count=integer(g.cycle_steps,"Variation.groove.cycle_steps",1,M.MAX_GROOVE_STEPS);if type(g.timing_offsets)~="table"or#g.timing_offsets~=count then die("Variation.groove.timing_offsets","cycle length mismatch")end;local fields={vc,integer(g.grid_num,"Variation.groove.grid_num",1,2147483647),integer(g.grid_den,"Variation.groove.grid_den",1,2147483647),count,math.floor(math.max(0,math.min(100,tonumber(v.groove_strength)or tonumber(v.swing)or 0))*1000+0.5)};for gi=1,count do fields[#fields+1]=integer(g.timing_offsets[gi],"Variation.groove.timing_offsets["..gi.."]",-960,960)end;add(w,M.TAG.GROOVE,fields)end;local lane_refs={};for lno,l in ipairs(v.lanes)do if lane_refs[l.id]then die("Lane["..lno.."].id","duplicate lane ID in variation")end;lane_refs[l.id]=hid(l.id,"Lane.id")end
    for _,l in ipairs(v.lanes)do tick();lc=lc+1;if lc>M.MAX_LANES then die("Lane","capacity exceeded")end;local pad=assert(pads[l.pad_id],"unknown lane pad");add(w,M.TAG.LANE,{lane_refs[l.id],vc,integer(pad.logical_index,"Lane.pad",1,128),integer(l.step_count,"Lane.step_count",1,4096),integer(l.division_num,"Lane.division_num",1,2147483647),integer(l.division_den,"Lane.division_den",1,2147483647),integer(l.phase,"Lane.phase",0,l.step_count-1),math.floor(l.swing*1000+0.5),math.floor(math.max(0,math.min(200,tonumber(l.velocity_sensitivity) or 100))*100+0.5),l.groove_enabled==false and 0 or 1})
     for _,s in ipairs(l.steps)do tick();sc=sc+1;if sc>M.MAX_STEPS then die("Step","capacity exceeded")end;locks=locks+#s.parameter_locks;if locks>M.MAX_LOCKS then die("ParameterLock","capacity exceeded")end;local rn,rd=rat(s.repeat_spacing,"Step.repeat_spacing");local ck,ca,cb=condition(s.condition,"Step.condition",lane_refs);add(w,M.TAG.STEP,{s.cut and 2 or(s.enabled and(s.runtime_one_shot and 3 or 1)or 0),integer(s.velocity,"Step.velocity",1,127),integer(s.pitch_semitones,"Step.pitch_semitones",-96,96),integer(s.pitch_cents,"Step.pitch_cents",-100,100),s.pan_lock==false and 1001 or integer(s.pan_lock,"Step.pan_lock",-100,100),integer(s.repeat_count,"Step.repeat_count",1,64),rn,rd,ppm(s.probability,"Step.probability"),integer(s.timing_offset,"Step.timing_offset",-960,960),ppm(s.gate,"Step.gate"),ck,ca,cb,s.slide and 1 or 0,#s.parameter_locks});for _,k in ipairs(s.parameter_locks)do tick();local kind,val=type(k.value)=="boolean"and 1 or type(k.value)=="number"and 2 or nil;if not kind then die("ParameterLock.value","runtime supports boolean or numeric values")end;val=kind==1 and(k.value and 1 or 0)or k.value;add(w,M.TAG.LOCK,{hid(k.parameter_id,"ParameterLock.parameter_id"),kind,val,hid(k.interpolation,"ParameterLock.interpolation")})end end
   end
  end
 end
 add(w,M.TAG.END_,{});if #w>M.MAX_WORDS then die("payload","word capacity exceeded")end;w[4]=#w;w[9]=#(rack.patterns or{});w[10]=vc;w[11]=lc;w[12]=sc;w[13]=#(rack.pads or{});w[14]=locks;w[15]=#groups;w[5]=checksum(w,6);return{words=w,revision=rev,active_variation=active,pending_variation=pending,checksum=w[5]}
end
function M.decode(words)
 if type(words)~="table"then return nil,"payload: array required"end;if #words<18 then return nil,"payload: truncated header"end;if words[1]~=M.MAGIC or words[2]~=M.VERSION then return nil,"payload: unsupported magic/version"end;if words[4]~=#words or #words>M.MAX_WORDS then return nil,"payload: length mismatch"end;if words[5]~=checksum(words,6)then return nil,"payload: checksum mismatch"end
 local i=17;while i<=#words do local tag,n=words[i],words[i+1];if type(n)~="number"or n<0 or n~=math.floor(n)or i+1+n>#words then return nil,"payload: malformed/truncated record"end;i=i+2+n;if tag==M.TAG.END_ then if n~=0 or i~=#words+1 then return nil,"payload: invalid terminator"end;return{revision=words[6],active_variation=words[7],pending_variation=words[8],patterns=words[9],variations=words[10],lanes=words[11],steps=words[12],pads=words[13],locks=words[14],groups=words[15],words=#words,checksum=words[5]}end end;return nil,"payload: missing terminator"
end
function M.publish(host,name,base,image)
 base=integer(base or 0,"base",0,700000);assert(type(host.gmem_attach)=="function"and type(host.gmem_write)=="function","gmem host required");host.gmem_attach(name or"ReaDrumSnapshot");host.gmem_write(base,0);for i,v in ipairs(image.words)do host.gmem_write(base+8+i,v)end;host.gmem_write(base+2,#image.words);host.gmem_write(base+3,image.checksum);host.gmem_write(base+4,image.revision);host.gmem_write(base+1,M.VERSION);host.gmem_write(base,M.MAGIC);return true
end
return M
